### ISSUE TITLE
Support for parallel_tests gem?

### ISSUE THREAD

**Issue by mattpickle** [ArturT/knapsack#10]
Would Knapsack work with CircleCI & parallel_tests gem?

**Comment by ArturT** [comment]
It should work but I didn't try it yet. You need to set proper values for `CI_NODE_TOTAL` and `CI_NODE_INDEX`.

I see that parallel_tests has `TEST_ENV_NUMBER` but it starts from 1 so you need to assign it in a way like this:
```
CI_NODE_TOTAL=4 # let's say you have 4 process
CI_NODE_INDEX=TEST_ENV_NUMBER-1
```

We can use execute option:
```
parallel_test -n 4 -e 'ruby -e "CI_NODE_TOTAL=4 CI_NODE_INDEX=#{ENV[:TEST_ENV_NUMBER].to_i-1} bundle exec rake knapsack:rspec"'
```

@mattpickle Let me know if that works for you. :)

**Comment by myers** [comment]
> Would Knapsack work with CircleCI & parallel_tests gem?

You probably just want to use the system built into parallel_tests that can split test up into groups.

**Comment by ArturT** [comment]
I created the example for parallel_tests and knapsack_pro gem:
https://github.com/KnapsackPro/knapsack_pro-ruby#how-to-run-knapsack_pro-with-parallel_tests-gem
