### ISSUE TITLE
Teach Knapsack about Timecop?

### ISSUE THREAD

**Issue by tmorris-fiksu** [ArturT/knapsack#11]
One of our longest specs has this line:
  before(:all) do
    Timecop.freeze(Time.new(2014, 6, 10, 11, 11, 11))
    ...
  end

However, Knapsack them believes that the entire file takes 0 seconds to run.

Would it make sense (and be relatively easy?) for Knapsack to simply bypass Timecop completely when computing metrics?  i.e. maybe shell out to the system to get the "real" time, regardless of the shenanigans Timecop is playing w/ Ruby's clock?

**Comment by ArturT** [comment]
That's interesting case. I will try to look at the issue this week. For now maybe this will help, here is the start and stop timer:
https://github.com/ArturT/knapsack/blob/master/lib/knapsack/tracker.rb#L22
https://github.com/ArturT/knapsack/blob/master/lib/knapsack/tracker.rb#L26

If you could solve the problem somehow I would be happy to see a pull request.

**Comment by tmorris-fiksu** [comment]
Well, this isn't quite ready for a PR, as it breaks your specs that rely on Timecop!
This did seem to work for my project:
https://github.com/tmorris-fiksu/knapsack/commit/1f461311b99fc713f7e586120340fcaddabe5748
Feel free to use it for motivation or a starting point for a complete patch.

**Comment by ArturT** [comment]
Cool. I will take a look.

**Comment by ArturT** [comment]
I released a new gem version. Check it out! :) Thanks for reporting this issue.
