### ISSUE TITLE
Minitest Adapter

### ISSUE THREAD

**Issue by 3zcurdia** [ArturT/knapsack#14]
This gem looks awesome and solve the problem of balancing tests but on our project we only run tests with minitest. I will be possible to get a minitest adapter?

**Comment by ArturT** [comment]
@3zcurdia Would be great to have it if you could create a pull request. It should be easy to add new adapter if you know minitest well. Here are current adapters:
https://github.com/ArturT/knapsack/tree/master/lib/knapsack/adapters

Let me know if you can help with that.

**Comment by 3zcurdia** [comment]
I am happy to help, but right now I found that is more complex than I imagined, let me explain what I found and maybe you could provide some feedback. I found in the adapters that the methods to call on knapsack are encapsulated inside of after/before config blocks for RSpec or similar on Cucumber, unfortunately on minitest doesn't have a this config blocks, on minitest you could do that overriding a methods called `setup` and `teardown` so the other option that I found was to make a minitest plugin which it looks more easy to integrate but the introduction of a plugin it might change the current abstraction of the adapter

**Comment by ArturT** [comment]
You can use `before()` and `after()` and use `::Kernel.at_exit` to execute something after all test suite, similar as here
https://github.com/ArturT/knapsack/blob/master/lib/knapsack/adapters/cucumber_adapter.rb#L15

Here is article I found:
http://stackoverflow.com/a/5883960/905697

Knapsack adapter doesn't require before test suite block.

Let me know if you need more tips. Thanks for help!

**Comment by ArturT** [comment]
@3zcurdia Let me know if you can work on this. If not I will try to do something during the weekend.

**Comment by 3zcurdia** [comment]
So far I tried but the before block or setup method is still my main blocker, maybe you could find a better solution, I will keep digging and see what I could find, also I noticed that the adapters could be separated gems to avoid install unnecessary dependencies

**Comment by ArturT** [comment]
I will look on that today and let you know. 

Regarding adapters as separate gems, might be a good idea but for now I think it would be inconvenient for user. Right now knapsack doesn't require rspec or cucumber as dependency.

**Comment by ArturT** [comment]
I checked source of minitest and found this https://github.com/seattlerb/minitest/blob/master/lib/minitest/test.rb#L129-160

I created pull request https://github.com/ArturT/knapsack/pull/16 with code I did so far and added TODO list there. 
I will try to do more maybe during next week or weekend.

For now I stuck with getting test file path for current running test. If you want to play with code I did maybe you will figure out this. Pry debugger might be useful. 

BTW What version of minitest you are using? How you run your tests on CI? Are you doing this with `rake test` or in a different way? Are you using `test_helper.rb` file?

**Comment by ArturT** [comment]
I figured out how to get test file path but will have to improve it a bit. I will keep up to date list of done things in pull request https://github.com/ArturT/knapsack/pull/16

BTW Do you have test files with the same test class name in one test suite? For now it bothers me because I'm getting test file path by search file having the same name as test class.

**Comment by 3zcurdia** [comment]
Here my answers:

* Yes I run `rake test` but for parallel test on circle I used `ruby -I.:test -e "ARGV.each{|f| require f }" ${files[@]}` 
* Yes I use `test_helper.rb` is very convenient to config different gems like capybara
* Particular I use rspec syntax so class names does not matter and I could split tests without repeating class names, I never had to use the unit test syntax.

**Comment by ArturT** [comment]
@3zcurdia Thanks for answers. I didn't test rspec syntax yet but you can do it. 
You can find here info how to add minitest:
https://github.com/ArturT/knapsack/tree/minitest-adapter
Please check if command `$ KNAPSACK_GENERATE_REPORT=true bundle exec rake test` works for you. I will have to find open source project with minitest rspec syntax to test knapsack.

**Comment by 3zcurdia** [comment]
I ran the tests and well it didnt make it trought got an nil on test_path on line https://github.com/ArturT/knapsack/blob/minitest-adapter/lib/knapsack/adapters/minitest_adapter.rb#L63 here is the trace

    NoMethodError: NoMethodError: undefined method `gsub' for nil:NilClass
    ~/.rvm/gems/ruby-2.2.2/bundler/gems/knapsack-5aa3fedf8130/lib/knapsack/adapters/minitest_adapter.rb:63:in `test_path'
    ~/.rvm/gems/ruby-2.2.2/bundler/gems/knapsack-5aa3fedf8130/lib/knapsack/adapters/minitest_adapter.rb:20:in `before_setup'
    ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/testing/tagged_logging.rb:16:in `before_setup'
    ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/testing/setup_and_teardown.rb:40:in `before_setup'
    ~/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.0/lib/active_record/fixtures.rb:825:in `before_setup'
    ~/.rvm/gems/ruby-2.2.2/bundler/gems/knapsack-5aa3fedf8130/lib/knapsack/adapters/minitest_adapter.rb:63:in `test_path'
    ~/.rvm/gems/ruby-2.2.2/bundler/gems/knapsack-5aa3fedf8130/lib/knapsack/adapters/minitest_adapter.rb:20:in `before_setup'
    ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/testing/tagged_logging.rb:16:in `before_setup'
    ~/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/testing/setup_and_teardown.rb:40:in `before_setup'
    ~/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.0/lib/active_record/fixtures.rb:825:in `before_setup'

**Comment by ArturT** [comment]
@3zcurdia I changed the way how I get test file path. Could you check now if you can generate report for your test suite?

**Comment by ArturT** [comment]
@3zcurdia Good news, I've finished work on minitest adapter and it works on my test project https://github.com/KnapsackPro/rails-app-with-knapsack but would be great to have feedback from you. 

I updated readme on branch https://github.com/ArturT/knapsack/tree/minitest-adapter with info how to set up minitest. 
You can check code changes in pull request https://github.com/ArturT/knapsack/pull/16

Please let me know if it works for you then I will release new knapsack gem version.

**Comment by ArturT** [comment]
@3zcurdia I released knapsack v1.2.0 with minitest support. I'm closing this issue but please let me know if it works for you or if you find any bug please create a new issue. :) Hope this release will help you with your work. :)

**Comment by 3zcurdia** [comment]
I tested and it worked on circle-ci really nice! thanks!

**Comment by ArturT** [comment]
@3zcurdia So cool! BTW Check it out http://knapsack.launchrock.com I'm working on it and will let you know about beta release.
