### ISSUE TITLE
Compatibility with Turnip Features

### ISSUE THREAD

**Issue by greggroth** [ArturT/knapsack#18]
I have a test suite that is a mixture of spec files in `spec/**/*_spec.rb` and Turnip features in `spec/**/*.feature`.  I'm trying to generate the report on TravisCI and with the pattern `spec/**/*{_spec.rb,.feature}` it correctly runs all of the specs and turnip features; however the generated report doesn't include any of the features.  I've looked through the source of this project and didn't spot anything obvious that I thought could be to blame.  Do you have any thoughts on how I could go about troubleshooting this?

This is the command I'm using to run the tests:

```bash
KNAPSACK_TEST_FILE_PATTERN="spec/**/*{_spec.rb,.feature}" KNAPSACK_GENERATE_REPORT=true bundle exec rspec spec
```

**Comment by ArturT** [comment]
@greggroth Hi, I've just did quick test and pattern works in case when `.feature` file has rspec tests.

I guess your `.feature` file has cucumber test inside so in that case you need to generate a separate report for cucumber tests and use cucumber adapter:
https://github.com/ArturT/knapsack#step-for-cucumber

**Comment by greggroth** [comment]
The specs are written using the gherkin syntax, but are ran using rspec, e.g. `bin/rspec spec/features/logging_in.feature`.  Would that still require a separate report?  I would think it would be included in the rspec report.

**Comment by ArturT** [comment]
Hmm, so it looks like rspec hooks were not fired and that's why report doesn't have `.feature` files.
https://github.com/ArturT/knapsack/blob/master/lib/knapsack/adapters/rspec_adapter.rb#L9

Maybe you are using a separate spec_helper.rb for `.feature` and you missed to bind there `Knapsack::Adapters::RspecAdapter`.

If I will find some time during weekend I can prepare test suite with turnip to debug the problem unless you will figure out it earlier.

**Comment by greggroth** [comment]
Thank you for the hint!  I dug in and found it's an issue with `Knapsack::Adapters::RspecAdapter.test_path`'s ability to parse the filename from example metadata.  This is when running a turnip feature:

```
pry(#<RSpec::ExampleGroups::REDACTED::REDACTED>)> Knapsack::Adapters::RspecAdapter.test_path(::RSpec.current_example.metadata[:example_group])
=> "/Users/greggory/.gem/ruby/2.2.2/gems/turnip-1.2.4/lib/turnip/rspec.rb"
```

and with a normal spec file:

```
[1] pry(#<RSpec::ExampleGroups::REDACTED::REDACTED::REDACTED>)> Knapsack::Adapters::RspecAdapter.test_path(::RSpec.current_example.metadata[:example_group])
=> "./spec/models/user_spec.rb"
```

I'll dig in further and see if I can't put together a PR to improve this.

**Comment by ArturT** [comment]
Cool. You may want to take a look how I get the test file path in other adapters
https://github.com/ArturT/knapsack/tree/master/lib/knapsack/adapters

Please let me know if you will have something. In case you stuck I will help with that.
