### ISSUE TITLE
Incompatibility with earlier versions of minitest

### ISSUE THREAD

**Issue by dkniffin** [ArturT/knapsack#24]
In earlier version of minitest, `Minitest.after_run` isn't available. Instead, the method for doing that was `Minitest::Unit.after_tests`. I will submit a PR soon with a fix for this.

**Comment by dkniffin** [comment]
Is there a good way to test this?

**Comment by ArturT** [comment]
Right now I don't have a good idea how to test this across two minitest versions.

In rspec adapter I did similar workaround https://github.com/ArturT/knapsack/blob/master/lib/knapsack/adapters/rspec_adapter.rb#L10,L15

Please create PR then we will figure out something.

Thanks!

**Comment by ArturT** [comment]
Fixed in the PR https://github.com/ArturT/knapsack/pull/26
