### ISSUE TITLE
Load Knapsack tasks inside Rakefile

### ISSUE THREAD

**Issue by pragmaticivan** [ArturT/knapsack#29]
I got some errors when I was using dis Gem. The rake tasks is not being loaded.

I found ou that on the example project you're loading the tasks there: https://github.com/KnapsackPro/rails-app-with-knapsack/blob/master/Rakefile

If that's required, you should update the Documentation.

**Comment by ArturT** [comment]
Hi, it's already there https://github.com/ArturT/knapsack#common-step
Probably I should call this section "Common required step" to avoid confusion.

**Comment by pragmaticivan** [comment]
Sorry, I meant on Semaphore block.

**Comment by pragmaticivan** [comment]
Yes, would be better replacing or at least associating this at the Companies integration.

**Comment by ArturT** [comment]
I moved load tasks instruction to installation section.
https://github.com/ArturT/knapsack#installation

**Comment by pragmaticivan** [comment]
Cool, thanks :D

**Comment by ArturT** [comment]
Thanks for pointing this out. Hope no one will have similar problem. :)
