### ISSUE TITLE
Using Knapsack with shoulda_context

### ISSUE THREAD

**Issue by nikz** [ArturT/knapsack#32]
Hiya!

Knapsack looks great, thanks! 

On small problem - we're using the [shoulda-context](https://github.com/thoughtbot/shoulda-context) gem, and it seems like this is interfering with the test timing reporter. The JSON that's being generated is just:

```
{
  "/home/travis/.rvm/gems/ruby-2.1.4/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb": 183.92807483673096
}
```

Is there anything we can do to fix this up? Or is that what we're expecting?

Thanks!

**Comment by ArturT** [comment]
Hi,

It looks like we need a fix to handle the case when shoulda-context gem is available.
Could you create a pull request for that? Here is the adapter for minitest and the method `test_path` responsible for determining a test file path. Please take a look:
https://github.com/ArturT/knapsack/blob/master/lib/knapsack/adapters/minitest_adapter.rb#L49

**Comment by ArturT** [comment]
NOTE:
Here is PR fix for shoulda-context. https://github.com/thoughtbot/shoulda-context/pull/51
Once merged then we can close this issue.

**Comment by ArturT** [comment]
shoulda-context release 1.2.2 solves problem.
