### ISSUE TITLE
What does "leftover" mean?

### ISSUE THREAD

**Issue by deadlyicon** [ArturT/knapsack#33]
Can you please update the README to explain the difference between `Report specs:` and `leftover specs:`

thanks

**Comment by ArturT** [comment]
Thanks for pointing this out. I added explanation https://github.com/ArturT/knapsack#what-does-leftover-specs-mean

**Comment by monfresh** [comment]
Hello. I found this issue because I'm seeing leftover specs, but the link to the explanation above doesn't work anymore. Where can I find the explanation? Thanks!

**Comment by ArturT** [comment]
@monfresh Here is the link to explanation https://docs.knapsackpro.com/ruby/knapsack#what-does-leftover-specs-mean
