### ISSUE TITLE
Logger levels cannot be changed

### ISSUE THREAD

**Issue by edwinv** [ArturT/knapsack#43]
We are using the Knapsack rake task to start our RSpec test suite:

```
rake knapsack:rspec
```

Knapsack is putting a lot of information into our build output, due to the `Knapsack.logger.level` begin set to `INFO`. I've tried changing this level to a lower setting, but because Knapsack is calling the logger from the rake task, there is no way to influence the logger level.

Is there any way to lower the logger level for the rake task? Maybe an environment variable can be introduced to influence the log level?

**Comment by ArturT** [comment]
>  Maybe an environment variable can be introduced to influence the log level?

Sounds like a good idea. Could you prepare a PR, you can control logger level here:
https://github.com/ArturT/knapsack/blob/master/lib/knapsack.rb#L51

**Comment by ArturT** [comment]
@edwinv Could you try the newest knapsack gem version and check the readme to adjust log level https://github.com/ArturT/knapsack#how-can-i-change-log-level
