### ISSUE TITLE
Test sequence random ordering

### ISSUE THREAD

**Issue by aabrook** [ArturT/knapsack#44]
Apologies if this is not the right place to post this request.

It appears as though knapsack sequences tests in a particular order. The issue with this is it can hide caching issues an dependencies. A more ideal solution would be to randomise test ordering on each node and, potentially, across nodes. This would help catch cross test dependencies.

Cheers

**Comment by ArturT** [comment]
@aabrook Thanks for the nice idea. I think randomize test ordering on each node sounds doable. Randomize them across nodes might be more problematic because we want to run specific tests on the particular node.

**Comment by aabrook** [comment]
I can definitely appreciate the difficulty across nodes just due to ensuring that execution times are uniform. Maybe a `stretch goal` where test balancing can be within a time frame to jumble. I suspect only possible in the pro version to track what's going on between nodes.

**Comment by ArturT** [comment]
Are you using the pro version https://github.com/KnapsackPro/knapsack_pro-ruby so you could try testing cross node randomization?

**Comment by aabrook** [comment]
Currently using just this version. Reviewed the pro but, due to the lack of https, we chose to continue with this version.

**Comment by ArturT** [comment]
I added https to pro version recently. Feel free to try it.

**Comment by ArturT** [comment]
@aabrook BTW currently you can randomize your rspec tests by adding in `.rspec` file the line

    --order rand

Thanks to that you would have randomize tests per node. Rspec will randomize them no matter the order of given test files.

**Comment by ArturT** [comment]
Here is example how to pass argument to knapsack command:

```
$ bundle exec rake "knapsack:rspec[--order rand]"
```

another way is to set order in `spec_helper.rb`:

```ruby
# spec/spec_helper.rb
RSpec.configure do |config|
  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = :random
end
```

**Comment by aabrook** [comment]
Great thank you
