### ISSUE TITLE
Generate report on rails 5

### ISSUE THREAD

**Issue by nickpoorman** [ArturT/knapsack#45]
We recently upgraded to rails 5 which no longer uses rake and it seems that the reports are no longer generating. We're using minitest so we would run:

```
# Step for Minitest
$ KNAPSACK_GENERATE_REPORT=true bundle exec rake test
```

Now when we run the updated command the reports are not generated:

```
# Step for Minitest
$ KNAPSACK_GENERATE_REPORT=true bundle exec rails test
```

We cannot use rake because it no longer works with our tests. Is there another way to generate a report?

**Comment by ArturT** [comment]
Maybe something like this would work:
```
KNAPSACK_GENERATE_REPORT=true bundle exec rails test
```

I need to play with rails 5 and check how it works.

**Comment by ArturT** [comment]
@nickpoorman I've just noticed my previous answer was the same solution you already tried. Sorry for that, I wrote that post during late hours :)

It might be possible to generate report with this:
```ruby
KNAPSACK_GENERATE_REPORT=true bundle exec rake knapsack:minitest
```

I will try to take a look at this issue during a weekend and I will update readme.

**Comment by ArturT** [comment]
@nickpoorman I updated readme in knapsack gem. I did a few tests today for rails 5 and above solution should work. Please let me know if you will find any problem.

I also create an example rails5 app with knapsack gem https://github.com/KnapsackPro/rails-app-with-knapsack/tree/rails5
