### ISSUE TITLE
Build fails with custom KNAPSACK_TEST_FILE_PATTERN

### ISSUE THREAD

**Issue by antonpaisov** [ArturT/knapsack#48]
https://github.com/ArturT/knapsack#how-can-i-run-tests-from-multiple-directories using the approach described here `bundle exec rake knapsack:rspec` fails with `require': cannot load such file -- spec_helper (LoadError)` when `KNAPSACK_TEST_FILE_PATTERN` contains other directories.

**Comment by ArturT** [comment]
Did you try to provide `KNAPSACK_TEST_DIR=directory_where_is_spec_helper` ?

**Comment by antonpaisov** [comment]
Yes, I've tried both with `KNAPSACK_TEST_DIR=spec` and without `KNAPSACK_TEST_DIR`

**Comment by ArturT** [comment]
How your KNAPSACK_TEST_FILE_PATTERN looks like? 

Maybe you require spec_helper from the wrong directory. For instance, in test file you require rails_helper but inside of rails_helper you require spec_helper from wrong directory (different then KNAPSACK_TEST_DIR).

I'm trying to reproduce that on this app: https://github.com/KnapsackPro/rails-app-with-knapsack
You could fork that and add the second test directory and pattern you use to reproduce problem.

I guess something like this:
```
KNAPSACK_TEST_DIR=spec KNAPSACK_TEST_FILE_PATTERN="{spec,spec2}/**{,/*/**}/*_spec.rb" bundle exec rake knapsack:rspec
```

If you have shared examples or code that should be shared across multiple directories like spec_helper then the spec_helper should be in directory that rspec use as default directory of your test suite KNAPSACK_TEST_DIR=spec. I'm not sure if you can specify multiple default paths for rspec `--default-path`:

https://github.com/ArturT/knapsack/blob/master/lib/knapsack/runners/rspec_runner.rb#L15

**Comment by antonpaisov** [comment]
Thank you @ArturT, my understanding of the problem is similar to what you've described.
I'll try to reproduce it on the test app :) Will get back to you about the results.

**Comment by antonpaisov** [comment]
So it turns out that `require_relative 'spec_helper'` instead of `require 'spec_helper'` in those others BCs fixed the problem.
Might be worth adding some tip about a possibility of such problem in Readme :)

**Comment by ArturT** [comment]
I've added tip here https://github.com/ArturT/knapsack#how-can-i-run-tests-from-multiple-directories

**Comment by antonpaisov** [comment]
Cool! (but it should be vise versa)
```
# good
require_relative 'spec_helper'

# bad - won't work
require 'spec_helper'
```

**Comment by ArturT** [comment]
Fixed. :)

**Comment by arturopie** [comment]
Hi, I'm having a similar issue, but the tip does not work. Is the value of `KNAPSACK_TEST_DIR` supposed to be used as the `--default-path` option?

**Comment by arturopie** [comment]
FYI, it works when I use `RUBYLIB=spec`

**Comment by ArturT** [comment]
Hi @arturopie 

> Is the value of KNAPSACK_TEST_DIR supposed to be used as the --default-path option?

Yes.

We exchanged emails before about [knapsack_pro](https://knapsackpro.com). The docs are here and you can set the test directory with your `spec_helper.rb` configuration with variable `KNAPSACK_PRO_TEST_DIR=spec` (note there is PRO in the name)
https://github.com/KnapsackPro/knapsack_pro-ruby#how-can-i-run-tests-from-multiple-directories

**Comment by antonpaisov** [comment]
btw, I had that issue of not having `_PRO_` in the variable name after migrating on knapsack_pro and that have resulted in some part of the test suite not running for some time, maybe you can somehow add some check for proper variable names? :)

**Comment by jhirn** [comment]
Hi. I'm not really sure from the examples how to do this. I have an integration suite in `integration/features` which all have their `require spec_helper`. I've changed this to require_relative `../../spec/spec_helper` which appears to start loading the spec_helper, but then require fails inside of the spec for things relative to that. For example, requiring files in `spec/support`.

 Here is the command I'm trying to use to run one of those tests. 

```bash
KNAPSACK_TEST_DIR="integration/features" KNAPSACK_REPORT_PATH="spec/knapsack/knapsack_integration_report.json" KNAPSACK_TEST_FILE_PATTERN=integration/features/**{,/*/**}/*_spec.rb bundle exec knapsack rspec integration/features/authentication_spec.rb
```

I've tried a few combinations with test dir, 
What is the least disruptive way to load the spec helper from the specs in `integration/features` where I won't have to and execute the tests in `integration/features` without having to resort to using require_relative for everything. 

We're successfully using knapsack on the standard specs in `spec/` . I just need a separate task for the integration spec which uses a different report. (or do I)?

Hope to hear back from ya, would really love to slice the time for these tests by /2 or more.

**Comment by ArturT** [comment]
Hi @jhirn 

Is your `spec_helper.rb` and `rails_helper.rb` in `spec` directory? Do you want to load it?

Or do you have separate `spec_helper.rb` and `rails_helper.rb` inside of `integration` directory? (I assume you have spec and integration on the same directory level (the integration directory is NOT inside of spec directory, right?)

Note `KNAPSACK_TEST_DIR` must point to a directory with `spec_helper.rb` and `rails_helper.rb` that you want to use.

You should not add list of test files at the end of knapsack command (`integration/features/authentication_spec.rb` will be ignored because tests are run based on `KNAPSACK_TEST_FILE_PATTERN` pattern)

```
# wrong
bundle exec knapsack rspec integration/features/authentication_spec.rb
```

You may want to try:

```
# spec_helper.rb/rails_helper.rb is inside of integration directory
KNAPSACK_TEST_DIR="integration" KNAPSACK_REPORT_PATH="spec/knapsack/knapsack_integration_report.json" KNAPSACK_TEST_FILE_PATTERN="integration/features/**{,/*/**}/*_spec.rb" bundle exec knapsack rspec
```

If you still have a problem you can share backtrace error.

You may also check how this is done in `knapsack_pro` gem ([it has free plan](https://knapsackpro.com/)) which has more options to configure different scenarios. 

* https://knapsackpro.com/faq/question/how-can-i-run-tests-from-multiple-directories
* https://knapsackpro.com/faq/question/how-to-run-tests-from-a-specific-directory-only-system-tests-or-features-specs
* https://knapsackpro.com/faq/question/how-to-run-only-rspec-feature-tests-or-non-feature-tests
* https://knapsackpro.com/faq/question/how-to-exclude-tests-from-running-them
* https://knapsackpro.com/faq/question/how-to-run-a-specific-list-of-test-files-or-only-some-tests-from-test-file

**Comment by jhirn** [comment]
Hey @ArturT , 

Thanks getting back to me. 

So I was able to get this working with the command you suggested and by creating `integration/spec_helper.rb` and adding to it `require_relative '../spec/spec_helper`. I ended up having to change a few `require`s in there to `require_relative` but only for local files. It's running locally to time to push up and see what circle says. 

Again, really appreciate your help. It might be useful to add "recipe" to the docs. It wasn't clear to me that `KNAPSACK_TEST_DIR` is where the spec_helper had to be and it's nifty to just `require_relative` what already exists.

**Comment by ArturT** [comment]
@jhirn I'm glad you managed to solve the problem. 

> Again, really appreciate your help. It might be useful to add "recipe" to the docs. It wasn't clear to me that `KNAPSACK_TEST_DIR` is where the spec_helper had to be and it's nifty to just `require_relative` what already exists. 

There is already info in the readme about spec_helper had to be in `KNAPSACK_TEST_DIR`. :)
https://docs.knapsackpro.com/ruby/knapsack#how-can-i-run-tests-from-multiple-directories
