### ISSUE TITLE
Knapsack crashes because exitstatus is nil

### ISSUE THREAD

**Issue by phansch** [ArturT/knapsack#53]
First of all, thank you very much for knapsack and maintaining it!

Since a few days we are getting crashes from knapsack in one of our builds because the exitstatus is nil:

```
rake aborted!

TypeError: no implicit conversion from nil to integer

/home/travis/build/the/project/vendor/bundle/ruby/2.3.0/gems/knapsack-1.13.1/lib/knapsack/runners/rspec_runner.rb:18:in `exit'
```
It crashes in [rspec_runner.rb#L18](https://github.com/ilyasgaraev/knapsack/blob/master/lib/knapsack/runners/rspec_runner.rb#L18) because `exit` can not handle `nil` itself.

~I have yet to find the reason why the exitstatus is nil, but you have any ideas, that would be great.~
The reason for the exitcode being `nil` was an infinite recursion in another dependency.

I also tried looking into writing a patch, but I am not sure how knapsack should behave if the exitstatus is `nil`.

**Comment by ArturT** [comment]
> The reason for the exitcode being nil was an infinite recursion in another dependency.
By fixing this recursion your tests are green now again?

Probably the fix should be:
```
exit($?.exitstatus) unless $?.exitstatus == 0
```
I will look into that.

**Comment by ArturT** [comment]
I've just found out that link you provided to the rspec_runner.rb file is from forked repo.

This bug was already fixed in this PR: https://github.com/ArturT/knapsack/pull/52

@phansch Could you use the newest version 1.13.1 of knapsack gem from rubygems instead of fork?
