### ISSUE TITLE
Test not in the report

### ISSUE THREAD

**Issue by kernow** [ArturT/knapsack#59]
Hi,

Thanks for creating this gem, it's very useful. I have a questions regarding what happens when tests are not specified in the report. For example if I have an rspec report that contains:

    {
      "spec/A_spec.rb": 3.047823905944824,
      "spec/B_spec.rb": 3.047823905944824
    }

And if I add a new test file `spec/C_spec.rb` but I don't add it to the report will the tests in `spec/C_spec.rb` be run or will they be ignored and not run?

Thanks

**Comment by ArturT** [comment]
knapsack will figure out that there is a new test or if a test was removed but it won't know about test time execution to make right split hence you need once in a while to regenerate the report.

I created knapsack_pro gem to handle that and even more. It tracks all your branches and can do dynamic test allocation across CI nodes to get optimal test suite split. You can learn more here https://knapsackpro.com
