### ISSUE TITLE
custom configuration for the rake tasks

### ISSUE THREAD

**Issue by naw** [ArturT/knapsack#62]
I see in the README that you can provide custom configuration in `spec_helper.rb`, `test_helper.rb`, etc.

This affects the configuration when running tests and generating a report.

However, how do you provide configuration when running the knapsack rake tasks?

For example, I'm using rspec, and have a custom configuration to change the `report_path`.

This correctly saves the report where I want it to when I run `rspec` to generate the report, but how do I tell rake `knapsack:rspec` to use the alternate report location?

**Comment by ArturT** [comment]
You can use `KNAPSACK_REPORT_PATH`

```
KNAPSACK_REPORT_PATH="knapsack_custom_report.json" CI_NODE_TOTAL=2 CI_NODE_INDEX=0 bundle exec rake knapsack:rspec
```

You may want to check https://knapsackpro.com with more advanced features like Queue Mode to get optimal test suite split.

**Comment by naw** [comment]
Thanks. I see now that the environment variable is mentioned in the README; I just didn't see it.

**Comment by ArturT** [comment]
Cool. I'm closing the issue then.

BTW I recommend seeing video how Knapsack Pro Queue Mode works to get optimal test suite split.
https://www.youtube.com/watch?v=pkdLzKlnlQg
