### ISSUE TITLE
Docs for circleci 2.0

### ISSUE THREAD

**Issue by chevinbrown** [ArturT/knapsack#65]
Docs are helpful for circleci 1.0, but 2.0 has a lot of changes and weak documentation. This is just a request to update docs for those of us migrating to 2.0!

**Comment by ArturT** [comment]
Feel free to help make a pull request with updated readme about CircleCI 2.0.

I did a basic example in knapsack_pro gem here https://github.com/KnapsackPro/knapsack_pro-ruby#info-for-circleci-users so you could use it as inspiration. Probably you are more up to date with recent changes in CircleCI 2.0.

**Comment by ArturT** [comment]
I've updated readme.
