### ISSUE TITLE
Cucumber 3 support

### ISSUE THREAD

**Issue by iain** [ArturT/knapsack#67]
I'm getting `uninitialized constant Cucumber::RbSupport (NameError)`

**Comment by ArturT** [comment]
What exactly version of Cucumber do you have?

**Comment by iain** [comment]
Cucumber 3.0.1

I've made the following workaround:

``` ruby
  around = method(:Around)
  Knapsack::Adapters::CucumberAdapter.class_eval do
    define_method :Around do |*args, &block|
      around.call(*args, &block)
    end
  end
```

**Comment by igas** [comment]
I experience the same issue. Also on 3.0.1.

**Comment by ArturT** [comment]
Ok. I will have to add support for Cucumber 3 then in https://github.com/ArturT/knapsack/blob/master/lib/knapsack/adapters/cucumber_adapter.rb

**Comment by ArturT** [comment]
FYI The workaround proposed by @iain does not work. The code is running but the hook is not called. 

I found how to use `around` hook in Cucumber 3 here https://github.com/cucumber/cucumber-ruby/blob/v3.0.0/lib/cucumber/glue/dsl.rb

I prepared fix here: https://github.com/ArturT/knapsack/pull/68

I've released a new version of `knapsack` and `knapsack_pro` gem. You can learn more how to speed up your tests with advanced pro version here: https://knapsackpro.com

Thanks for reporting issue! 👍
