### ISSUE TITLE
cannot load such file -- knapsack After install

### ISSUE THREAD

**Issue by joshfng** [ArturT/knapsack#69]
Followed the install instructions. I'm able to run regular rspec and generate the knapsack report, but when I try to run the knapsack rake task I get the load error:

Rails 4.2

```
LoadError:
  cannot load such file -- knapsack
```

Gemfile
```
group :development, :test do
...
gem 'knapsack'
...
```

Rakefile
```
require File.expand_path('../config/application', __FILE__)

Myapp::Application.load_tasks
Knapsack.load_tasks if defined?(Knapsack)
```

rails_helper.rb
```
ENV['RAILS_ENV'] = 'test'

require File.expand_path("../../config/environment", __FILE__)

require 'knapsack'
Knapsack::Adapters::RSpecAdapter.bind
```

Has anyone else experienced this?

**Comment by joshfng** [comment]
Seems the issue is any require when executing `bundle exec rake knapsack:rspec`

No matter what file is required first it always reports that there's no such file

**Comment by ArturT** [comment]
You can take a look at example project:
https://github.com/KnapsackPro/rails-app-with-knapsack/blob/master/Rakefile

Why you have double `..` ? It should be `require File.expand_path('../config/application', __FILE__)` in regular rails app. Is your project in a different directory?

**Comment by joshfng** [comment]
Thanks for the reply!

My Rakefile is correct: `require File.expand_path('../config/application', __FILE__)` I think you were looking at the rails_helper.rb file below.

When I run `bundle exec rspec` all files are loaded correctly. It's only when trying to run the `knapsack:rspec` task when files can no longer be found

**Comment by joshfng** [comment]
I've sourced the problem to https://github.com/ArturT/knapsack/blob/master/lib/knapsack/runners/rspec_runner.rb#L15

If I change:
```
bundle exec rspec #{args} --default-path #{allocator.test_dir} -- #{allocator.stringify_node_tests}
```

To
```
bin/rspec #{args} --default-path #{allocator.test_dir} -- #{allocator.stringify_node_tests}
```

It runs correctly

**Comment by ArturT** [comment]
Oh, it looks like the same problem was here https://github.com/ArturT/knapsack/issues/54 where someone forked the repo to fix it.

I'm not sure if I should do assumption in my gem that you always have bin/rspec. Maybe if knapsack could be configurable whether you want to use `bundle exec rspec` or `bin/rspec` would help.

**Comment by ArturT** [comment]
@joshfng You may want to try `knapsack_pro` gem which works in a different way and this problem should not occur. You can learn more watching video at https://knapsackpro.com
