### ISSUE TITLE
Want a recipe for working with rails systemtests in your docs?

### ISSUE THREAD

**Issue by colinxfleming** [ArturT/knapsack#71]
Hey @ArturT , thanks much for this, it's a lovely library and a huge time-saver for us at DCAF Engineering (and by extension, me personally).

We recently ported some integration tests over to system test (in minitest), and it took a little bit of poking around to get them to show up in the report -- `KNAPSACK_GENERATE_REPORT=true bundle exec rake test test:system` in CI wound up doing the trick.

I thought I'd make a PR to the docs describing how to get systemtests to show up in the report to pay it forward, but wanted to check with you first and make sure this wouldn't be intrusive. Let me know if this is something that would be helpful.

**Comment by ArturT** [comment]
Hey @colinxfleming, thanks for nice words. It would be nice if you could prepare the PR with updated README. :)

**Comment by colinxfleming** [comment]
You betcha. I'll pop that out shortly.
