### ISSUE TITLE
Rails is not loaded in my spec_helper.rb

### ISSUE THREAD

**Issue by ibrahima** [ArturT/knapsack#72]
I'm using simplecov with my rspec suite, so I want to eager load all my application code so that my coverage stats actually include all the code in my application. Knapsack worked fine before I added the eager loading to my spec_helper, but once I added this, my test suite crashes because Rails is not defined:

in `spec_helper.rb`

```ruby
if ENV['UPLOAD_CODECOV']
  require 'simplecov'
  require 'codecov'
  SimpleCov.start 'rails' do
    formatter SimpleCov::Formatter::Codecov
  end

  Rails.application.eager_load!
end
```

I get this error: `uninitialized constant Rails (NameError)`.

I'm running Knapsack like this: `bundle exec rake knapsack:rspec`. Also tried with knapsack_pro, with the same results.

Any idea why Rails would not be defined here? Without this line, the specs will run, so at some point in the process Rails does get loaded, just not in my spec_helper.rb.

Thanks!

**Comment by ArturT** [comment]
If you use `rails_helper.rb` then `Rails` const should be available after you load Rails environment:

```ruby
# spec/rails_helper.rb
ENV['RAILS_ENV'] ||= 'test'
require 'spec_helper' # here we load spec_helper
require File.expand_path('../../config/environment', __FILE__) # this will load Rails

# here Rails should be defined
```

**Comment by ibrahima** [comment]
Oh huh, good point! Wonder why it worked before, perhaps in the standard configuration it happens to load the app earlier anyway.
