### ISSUE TITLE
Parallel executing inside Docker

### ISSUE THREAD

**Issue by cobusbernard** [ArturT/knapsack#79]
Hi, we moved our app into Docker and are now running the tests inside the container via a compose file. Is it possible to still parallelize the execution? Currently we are doing something like: ```@docker-compose -f ./docker-compose.test.yml run -e RAILS_ENV=test platform bash -c "bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake knapsack:rspec``` 
Previously we were able to run with 4 worker nodes on CirceCI 2.0, would love to get back to that.

**Comment by ArturT** [comment]
Here is an example of CircleCI 2.0 configuration for parallelization: http://docs.knapsackpro.com/2017/circleci-2-0-capybara-feature-specs-selenium-webdriver-with-chrome-headless

```
# .circleci/config.yml
jobs:
  build:
    parallelism: 6
```

If you manually define the knapsack command to run on each CI node ensure the CircleCI environment variables are exposed inside of the container or manually pass them.

for instance: `CI_NODE_TOTAL=2 CI_NODE_INDEX=0 bundle exec rake knapsack:rspec`

http://docs.knapsackpro.com/ruby/knapsack#step-2

**Comment by cobusbernard** [comment]
Thanks @ArturT. How would you use this with docker compose? I'm trying to run knapsack + rspec inside the container?

**Comment by cobusbernard** [comment]
@ArturT: just tested and all I need to do is pass in the env var `CIRCLE_NODE_TOTAL` to the compose command and it uses the additional nodes. Going to close this issue now.
