### ISSUE TITLE
Knapsack misses tests due to different glob result ordering

### ISSUE THREAD

**Issue by mhildreth-fiksu** [ArturT/knapsack#8]
We have been using Knapsack to split RSpec on our builds on Travis, and have experienced an issue where some leftover specs would not be run on any of the jobs of a single build. Here is an example of the issue that we are having.

Assume we have the following specs:

* spec/a.rb
* spec/b.rb
* spec/c.rb
* spec/d.rb
* spec/e.rb

When running, we might get something like the following on run one...

```bash
$ export CI_NODE_TOTAL=2
$ export CI_NODE_INDEX=0
$ bundle exec rake "knapsack:rspec[--profile 10]"
...
Leftover specs:
spec/a.rb
spec/c.rb
spec/e.rb
```

However, on job two, we get something like this...

```bash
$ export CI_NODE_TOTAL=2
$ export CI_NODE_INDEX=1
$ bundle exec rake "knapsack:rspec[--profile 10]"
...
Leftover specs:
spec/c.rb
spec/a.rb
```

Note that "b" is not run on either spec, and that "a" is run on both. Also, note that "a" comes before "c" in the first run, but after "c" in the second run.

The best reason I can come up with is the fact that when [Knapsack globs for tests](https://github.com/ArturT/knapsack/blob/1ecc205fe253aabf6b0d3203e9352785c990a669/lib/knapsack/distributors/base_distributor.rb#L36), it does not then order them. This doesn't matter for the tests with times reported, since the [report distributor appears to use the test run time to sort before assigning to nodes](https://github.com/ArturT/knapsack/blob/1ecc205fe253aabf6b0d3203e9352785c990a669/lib/knapsack/distributors/report_distributor.rb#L5). However, the order in which files are returned [would matter when assigning leftover tests](https://github.com/ArturT/knapsack/blob/1ecc205fe253aabf6b0d3203e9352785c990a669/lib/knapsack/distributors/leftover_distributor.rb#L8-L10).

I still am not sure exactly why in two separate jobs, Travis is returning the list of files with different orders (I would think that both running on the same operating system, they would return the same order). However, this can all be avoided by sorting the test files in a consistent way, either [when they are first retrieved](https://github.com/ArturT/knapsack/blob/1ecc205fe253aabf6b0d3203e9352785c990a669/lib/knapsack/distributors/base_distributor.rb#L36) or [when determining the leftover tests](https://github.com/ArturT/knapsack/blob/1ecc205fe253aabf6b0d3203e9352785c990a669/lib/knapsack/distributors/leftover_distributor.rb#L8-L10). That way, Knapsack is not relying on the `Dir` method's ordering (which [according to the documentation "depends on your system"](http://ruby-doc.org/core-2.2.0/Dir.html#glob-method)) for proper distribution.

**Comment by ArturT** [comment]
@mhildreth-fiksu Hi, Thanks for reporting issue. I did fix with sort https://github.com/ArturT/knapsack/commit/54304cb3159ad87548e4a5af9be508acce960d4a

Could you try use gem via github?
```
  gem 'knapsack', github: 'ArturT/knapsack'
```

Let me know if it helped. I will release a new gem version tomorrow then.

**Comment by mhildreth-fiksu** [comment]
Just tried this out. The new version worked as expected.

Thanks for the quick response!

**Comment by ArturT** [comment]
@mhildreth-fiksu FYI I've just released a new gem version. Thanks for help!

**Comment by rishijain** [comment]
I am not sure if this has cropped up again, because there are specs in travis build which are coming under leftover specs and is never run in any of the 10 threads in travis.

I am using version `1.13.0`. Anyone has any thoughts on this?

**Comment by ArturT** [comment]
@rishijain You can try to update the gem to the latest version.
https://github.com/ArturT/knapsack/blob/master/CHANGELOG.md


The specs might end up in leftovers if they are empty test files or only pending test files but never the less they should be executed by RSpec.

https://github.com/ArturT/knapsack#why-some-of-test-files-are-still-in-leftover-specs-after-i-generate-a-new-report

Do you use any custom configuration like explicitly defined `KNAPSACK_TEST_FILE_PATTERN`?

You can also try to reproduce the bug on this example repo with installed `knapsack` gem.
https://github.com/KnapsackPro/rails-app-with-knapsack

BTW I've released a new website today for https://knapsackpro.com
