### ISSUE TITLE
send complete test coverage report from circleCI building specs to codeclimate

### ISSUE THREAD

**Issue by andreleoni** [ArturT/knapsack#84]
Hello, I want to send my complete test coverate report to codeclimate, but with knapsak, the tests are splitted, and the report is not complete.

Hava anyway to resolve this problem? :thinking:

**Comment by ArturT** [comment]
Here you will find a link to CodeClimate resources that might be useful
https://github.com/KnapsackPro/knapsack_pro-ruby#how-to-use-codeclimate-with-knapsack_pro

**Comment by andreleoni** [comment]
I will test, but I that is it!!!!!

Many many many thannks man!!

**Comment by ArturT** [comment]
@andreleoni If you have a larger project with long test suite you may find this useful what problems can be solved with dynamic test suite split: https://youtu.be/hUEB1XDKEFY

I also added support for Cypress test runner in javascript:
https://docs.knapsackpro.com/2018/run-javascript-e2e-tests-faster-with-cypress-on-parallel-ci-nodes
