### ISSUE TITLE
Generate report on minitest

### ISSUE THREAD

**Issue by flavono123** [ArturT/knapsack#87]
I've got following errors:
```ruby
$ KNAPSACK_GENERATE_REPORT=true bundle exec rake knapsack:minitest
rake aborted!
Knapsack report file knapsack_minitest_report.json doesn't exist. Please generate report first!
/Users/hong/.rbenv/versions/2.5.3/bin/bundle:23:in `load'
/Users/hong/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'

Caused by:
Errno::ENOENT: No such file or directory @ rb_sysopen - knapsack_minitest_report.json
/Users/hong/.rbenv/versions/2.5.3/bin/bundle:23:in `load'
/Users/hong/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'
Tasks: TOP => knapsack:minitest
(See full trace by running task with --trace)
```

It seemed there is no creating the report file at the first time, just open/write it, in codes. But this doc says like it should be created: 
https://docs.knapsackpro.com/ruby/knapsack#common-step

Is it gonna fixed?

I solved this problem with creating an empty json report file manually

**Comment by ArturT** [comment]
What version of Ruby, Ruby on Rails, minitest do you use?

```
# If you use Rails 5 then run this instead:
$ KNAPSACK_GENERATE_REPORT=true bundle exec rake knapsack:minitest

# If you use Rails 5.1's SystemTest, run both unit and system tests
$ KNAPSACK_GENERATE_REPORT=true bundle exec rake test test:system
```

Have you set config at the top:

Add at the beginning of your test_helper.rb:

```ruby
require 'knapsack'

# CUSTOM_CONFIG_GOES_HERE

knapsack_adapter = Knapsack::Adapters::MinitestAdapter.bind
knapsack_adapter.set_test_helper_path(__FILE__)
```

https://docs.knapsackpro.com/ruby/knapsack#step-for-minitest

BTW How long is your test suite? What CI provider do you use?

**Comment by flavono123** [comment]
Ruby - 2.5.3
Rails - 5.2.1

I already added that config codes on my test helper.

And the command you suggested is exactly same with mine:
`KNAPSACK_GENERATE_REPORT=true bundle exec rake knapsack:minitest`

I use Travis CI and the test suit takes about 15 minutes.
The errors are occurred in my local.

**Comment by ArturT** [comment]
I have exactly the same versions of dependencies as you do and it works. You can compare your files with mine https://github.com/KnapsackPro/rails-app-with-knapsack/blob/master/test/test_helper.rb

I can try to reproduce error later evening when I will get back home. Maybe there is some other difference in your project that cause this problem :/

or you can try https://knapsackpro.com/ (article https://docs.knapsackpro.com/2018/how-to-run-travis-ci-parallel-jobs-with-build-matrix-feature-fast )

**Comment by flavono123** [comment]
Sorry for that I can show the codes to you since it is my company's property 😅
But the call stacks are followed I think:
```ruby
1. Knapsack::Runners::MinitestRunner.run(args[:minitest_args]) # lib/tasks/knapsack_minitest.rake L:5
2. allocator = Knapsack::AllocatorBuilder.new(Knapsack::Adapters::MinitestAdapter).allocator # lib/knapsack/runners/minitest_runner.rb L:5
3. report: Knapsack.report.open, # lib/knapsack/allocator_builder.rb L:10
4. report = File.read(report_path) # lib/knapsack/report.rb L:25
5. raise "Knapsack report file #{report_path} doesn't exist. Please generate report first!" # lib/knapsack/report.rb L:28
```

It seems try to open before create a report file right?

**Comment by ArturT** [comment]
Actually, the command you should run for the very first time should be `KNAPSACK_GENERATE_REPORT=true bundle exec rake test`. I will update the docs later. 

Or if still does not work then try to create `knapsack_minitest_report.json` file with this content:

```
{}
```

**Comment by flavono123** [comment]
Got it. `KNAPSACK_GENERATE_REPORT=true bundle exec rake test` not `knapsack:minitest` for the first time. It works

Hope that the docs gonna be clearer. ☺️  Thanks.

**Comment by ArturT** [comment]
@flavono123 Thanks for reporting the issue. I've just fixed docs.
