### ISSUE TITLE
All tests run when no spec files are found

### ISSUE THREAD

**Issue by kaoru** [ArturT/knapsack#88]
I'm trying to split my tests into two runs, one which runs the the system tests and one which runs the rest.

I'm implementing that with:

```
echo "--- system ---"
export KNAPSACK_TEST_FILE_PATTERN="spec/system/**{,/*/**}/*_spec.rb"
bundle exec rake "knapsack:rspec[--format=RspecTap::Formatter]"
```

The problem I've run into is that when there are no system tests that are scheduled to run on that node, it runs ***all the tests*** 😅 

```
Report specs:
Leftover specs:
Knapsack time offset warning enabled!
1..3597
```

I'd like it to run none of the tests, and exit with success.

Is that a bug in knapsack or in rspec, or is it the expected behaviour?

Thanks!

**Comment by ArturT** [comment]
When you pass no tests to RSpec via knapsack then RSpec runs the whole test suite.

I use [under the hood `Dir.glob` to find test files](https://github.com/ArturT/knapsack/blob/master/lib/knapsack/distributors/base_distributor.rb#L40) and then [pass them to RSpec](https://github.com/ArturT/knapsack/blob/master/lib/knapsack/runners/rspec_runner.rb#L15).

Why do you want to run pattern for non-existing tests?

What CI do you use?

**Comment by kaoru** [comment]
Hey Artur,

I'm using Heroku CI with Knapsack spreading the load across 16 nodes. I wanted to to run my system tests separately so I did this:

```
# Non-System Non-Feature tests
DIRECTORIES=$(find spec -mindepth 1 -maxdepth 1 -type d | grep -v system | sort | ruby -e 'puts STDIN.each_line.map { |p| p.sub(%r{^spec/}, "").chomp }.join(",")')
echo "--- $DIRECTORIES ---"
export KNAPSACK_TEST_FILE_PATTERN="spec/{$DIRECTORIES}/**{,/*/**}/*_spec.rb"
bin/rails "knapsack:rspec[--format=RspecTap::Formatter]"

# System and Feature tests
DIRECTORIES="system"
echo "--- $DIRECTORIES ---"
export KNAPSACK_TEST_FILE_PATTERN="spec/{$DIRECTORIES}/**{,/*/**}/*_spec.rb"
bin/rails "knapsack:rspec[--format=RspecTap::Formatter]"
```

But on two of the nodes the second run found no spec files, and so it ended up running the full test suite on those nodes :joy: 

I've "fixed" this by splitting it into non-feature-or-system-tests and feature-and-system-tests, which makes it so that every node ends up with tests in it, but it's a bit of a hack!

That said it's hacks on hacks because the fact that I need to run the system tests separately is already a hack working around a bit of a fragile test suite situation :sweat_smile: 

No worries if you just want to close this, I'm happy with my hacks for now :smile:

**Comment by ArturT** [comment]
Thanks for sharing your solution. You may want to check this article about Heroku CI setup for knapsack_pro gem:
https://docs.knapsackpro.com/2018/how-to-run-parallel-dynos-on-heroku-ci-to-complete-tests-faster

This video explains how Queue Mode in knapsack_pro does dynamic split tests across parallel nodes to ensure all nodes finish work at a similar time to get the fastest CI build time. https://youtu.be/hUEB1XDKEFY
