### ISSUE TITLE
cucumber runner exits with non-zero code even though tests passed

### ISSUE THREAD

**Issue by abhitrivedi** [ArturT/knapsack#89]
Hi. Im running v1.17.1 on Ruby 2.6.3 and Rails 5.2.3.

While running rake knapsack:cucumber, I get the following warning-like output after tests have completed successfully, and the command exists with a non-zero code. Naturally the non-zero code fails CI even though all tests passed.

```
121 scenarios (121 passed)
2091 steps (2091 passed)
1m15.349s

========= Knapsack Time Offset Warning ==========
Time offset: 30s
Max allowed node time execution: 01m 10s
Exceeded time: 04s

Tests on this CI node took more than max allowed node time execution.
Please regenerate your knapsack report.
If that didn't help then split your heavy test file
or bump time_offset_in_seconds setting.

Need explanation? See FAQ:
https://github.com/ArturT/knapsack#faq
=================================================
Sign up for Knapsack Pro here:
https://knapsackpro.com
=================================================

Knapsack global time execution for tests: 01m 15s

invalid option: --require

minitest options:
    -h, --help                       Display this help.
        --no-plugins                 Bypass minitest plugin auto-loading (or set $MT_NO_PLUGINS).
    -s, --seed SEED                  Sets random seed. Also via env. Eg: SEED=n rake
    -v, --verbose                    Verbose. Show progress processing files.
    -n, --name PATTERN               Filter run on /regexp/ or string.
        --exclude PATTERN            Exclude /regexp/ or string from run.

Known extensions: rails, pride
    -w, --warnings                   Run with Ruby warnings enabled
    -e, --environment ENV            Run tests in the ENV environment
    -b, --backtrace                  Show the complete backtrace
    -d, --defer-output               Output test failures and errors after the test run
    -f, --fail-fast                  Abort test run on first failure or error
    -c, --[no-]color                 Enable color in the output
    -p, --pride                      Pride. Show your testing pride!

> echo $?
1

**Comment by ArturT** [comment]
What version of cucumber do you use? What is your CI server?
Do you pass any additional arguments to knapsack cucumber command? Can you share how do you run it (what's the command you typed)? Thanks.

**Comment by abhitrivedi** [comment]
Cucumber version: 2.99.0
Cucumber-rails version: 1.4.0
Command: `bundle exec rake knapsack:cucumber`
ENV vars: `CI_NODE_TOTAL=4 CI_NODE_INDEX=0`
CI: Travis CI (although this is also reproducible locally)

**Comment by abhitrivedi** [comment]
I also tried `bundle exec knapsack cucumber` but got the same non-zero code (1).

**Comment by ArturT** [comment]
Here is example how knapsack executes cucumber:
https://github.com/ArturT/knapsack/blob/01cedac27e437b445bee2765a87cbbe53f458193/lib/knapsack/runners/cucumber_runner.rb#L15

Maybe this line messed up something for older Cucumber 2.99:
https://github.com/ArturT/knapsack/blob/01cedac27e437b445bee2765a87cbbe53f458193/lib/knapsack/runners/cucumber_runner.rb#L18

I have a project with cucumber test suite and knapsack that I use for testing.
There is cucumber 3.1.2
https://github.com/KnapsackPro/rails-app-with-knapsack/blob/ccb70faddc904422d694f7d263df062a7eec38f6/Gemfile.lock#L77

If you want to help debug it you can use this repo to run tests https://github.com/KnapsackPro/rails-app-with-knapsack

You can set local path `KNAPSACK_REPO_PATH` to the local clone of knapsack repo to test your changes in knapsack code.
https://github.com/KnapsackPro/rails-app-with-knapsack/blob/ccb70faddc904422d694f7d263df062a7eec38f6/Gemfile#L46

**Comment by ArturT** [comment]
I've just noticed what's wrong. The output you shared says:

```
invalid option: --require
```

So cucumber command failed because did not understand `--require` argument. It seems `--require` works only for Cucumber >= 3. I will try to see how to run tests in older Cucumber 2.x and make a fix.

**Comment by ArturT** [comment]
Cucumber 2.99 has `--require` argument so this is not error from cucumber.

Now I noticed that it's the error from minitest gem. Cucumber does not depend on minitest. I don't require minitest in the knapsack during load time. For some weird reason minitest is loaded when you run Cucumber and minitest breaks :/ I'm not sure what's the root problem yet.

```
invalid option: --require

minitest options:
```

I had a problem to downgrade cucumber-rails and cucumber so I used my old branch with rails4 to reproduce exactly your problem for:
Cucumber version: 2.99.0
Cucumber-rails version: 1.4.0
https://github.com/KnapsackPro/rails-app-with-knapsack/tree/rails4-cucumber2.99

@abhitrivedi Are you able to upgrade cucumber-rails and cucumber gem to 3.x?
Maybe this will be quicker than supporting outdated gems.

**Comment by ArturT** [comment]
I googled fix. 

You can add this in file `features/support/env.rb`.

```
# features/support/env.rb
require 'multi_test'
MultiTest.disable_autorun

# this mus be after miniest disable autorun
require 'cucumber/rails'
```

The solution from: https://github.com/cucumber/multi_test/pull/2#issuecomment-21863459

Related issue: https://github.com/cucumber/cucumber-rails/issues/252

**Comment by ArturT** [comment]
@abhitrivedi I've edited above example. We need to disable autorun for minitest after we load cucumber/rails.

**Comment by abhitrivedi** [comment]
@ArturT thanks for that in-depth analysis. I'll try that out and update you.

**Comment by abhitrivedi** [comment]
That worked!
We can't upgrade cucumber-rails right now due to an interna dependency, but i've notified the teams about this issue so hopefully we can upgrade soon. Thanks @ArturT for your help.

**Comment by ArturT** [comment]
@abhitrivedi Great! BTW Have you got my email today? We can also talk over LinkedIn. I've sent you an invitation.

**Comment by ArturT** [comment]
I've updated FAQ: https://github.com/KnapsackPro/knapsack_pro-ruby#why-green-test-suite-for-cucumber-299-tests-always-fails-with-invalid-option---require
