### ISSUE TITLE
Knapsack not generating report for rspec

### ISSUE THREAD

**Issue by evandam** [ArturT/knapsack#93]
I'm running knapsack through Docker, and I cannot seem to generate new reports.

I'm running `docker-compose run -e KNAPSACK_GENERATE_REPORT=true rails bundle exec rake "knapsack:rspec[...]"`, but the `knapsack_rspec_report.json` is not updated or generated after tests complete.

I would like to be able to generate a report for each parallel job and aggregate them afterwards, but if that is not possible I just need to be able to generate a report on a single node.

**Comment by evandam** [comment]
Closing out since this was an issue on my end. `Knapsack::Adapters::RSpecAdapter.bind` was not being run.

**Comment by ArturT** [comment]
Hi @evandam , what CI server do you use?

You can also check this video showing how to split tests in a dynamic way with Queue Mode
https://youtu.be/hUEB1XDKEFY to track all tests, all branches and commits.

**Comment by evandam** [comment]
Hey @ArturT, I'm using Buildkite but using the regular Knapsack gem, not the pro version.

**Comment by ArturT** [comment]
I've sent you a LinkedIn invitation, we could talk there :)
