### ISSUE TITLE
Hide Knapsack Time Offset Warning block?

### ISSUE THREAD

**Issue by IanVaughan** [ArturT/knapsack#95]
Having the following block print on after each test run (using guard) is quite intrusive.
Is there a way to hide it?
```
========= Knapsack Time Offset Warning ==========
Time offset: 30s
Max allowed node time execution: 01m 21s
Exceeded time: -01m 21s

Global time execution for this CI node is fine.
Happy testing!

Need explanation? See FAQ:
https://docs.knapsackpro.com/ruby/knapsack#faq
=================================================
See how to split tests in a dynamic way using Queue Mode to ensure all parallel nodes
finish work at a similar time even when your CI or random test execution is a bottleneck:
https://youtu.be/hUEB1XDKEFY

Sign up for Knapsack Pro here:
https://knapsackpro.com
=================================================

Knapsack global time execution for tests: 0.1936500072479248s

```

**Comment by ArturT** [comment]
Hey @IanVaughan 

You can try this

```ruby
require 'knapsack'

# CUSTOM_CONFIG_GOES_HERE
Knapsack.tracker.config({
  enable_time_offset_warning: false,
})

Knapsack::Adapters::RspecAdapter.bind
```

https://docs.knapsackpro.com/ruby/knapsack#custom-configuration


You can also check out `knapsack_pro` gem that has a free plan to split tests in a dynamic way across parallel CI nodes to ensure all nodes finish work at a similar time (this way CI build time is as fast as possible). See the last video here about Queue Mode https://docs.knapsackpro.com/2020/how-to-speed-up-ruby-and-javascript-tests-with-ci-parallelisation

I'm working nowadays on RSpec feature to split test files by test examples so large test files can be split automatically across nodes. If you would be interested to test it please let me know :)
